### ISSUE TITLE
An error occurred while saving or deleting a post.

### ISSUE THREAD

**Issue by wzyxdwll** [oplik0/nodebb-plugin-meilisearch#45]
* NodeBB version: 3.10.3

MeiliSearchCommunicationError: Not Found: http://nodebb.meother.com/indexes/post/documents?primaryKey=pid
    at /data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:183:27
    at step (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:104:23)
    at Object.throw (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:85:53)
    at rejected (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:76:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Mon Nov 11 2024 12:31:53 GMT+0000 (Coordinated Universal Time)","error":{"name":"MeiliSearchCommunicationError"},"exception":true,"os":{"loadavg":[0.97,0.77,0.53],"uptime":1667165.97},"process":{"argv":["/usr/bin/node","/data/install-script/nodebb/app.js"],"cwd":"/data/install-script/nodebb","execPath":"/usr/bin/node","gid":0,"memoryUsage":{"arrayBuffers":25874203,"external":30549219,"heapTotal":122417152,"heapUsed":90901808,"rss":441024512},"pid":74058,"uid":0,"version":"v20.18.0"},"stack":"MeiliSearchCommunicationError: Not Found: http://nodebb.meother.com/indexes/post/documents?primaryKey=pid\n    at /data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:183:27\n    at step (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:104:23)\n    at Object.throw (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:85:53)\n    at rejected (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:76:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","trace":[{"column":27,"file":"/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js","function":null,"line":183,"method":null,"native":false},{"column":23,"file":"/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js","function":"step","line":104,"method":null,"native":false},{"column":53,"file":"/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js","function":"Object.throw","line":85,"method":"throw","native":false},{"column":65,"file":"/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js","function":"rejected","line":76,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false}]}
2024-11-11T12:31:53.040Z [4567/74058] - error: MeiliSearchCommunicationError: Not Found: http://nodebb.meother.com/indexes/post/documents?primaryKey=pid
    at /data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:183:27
    at step (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:104:23)
    at Object.throw (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:85:53)
    at rejected (/data/install-script/nodebb/node_modules/meilisearch/dist/bundles/meilisearch.cjs.js:76:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

After this error occurred, I found that my nodeBB restarted, and I found that Chinese search seemed to have no effect

**Comment by oplik0** [comment]
Should be fixed in 0.7.2 - turns out it was just a dependency update... But all my tests broke in the meantime due to NodeBB (and Node) updates...
